# inherit_from: .rubocop_todo.yml
# inherit_from: ../.rubocop.yml

AllCops:
  # TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - Gemfile
    - db/schema.rb
    - bin/*
Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false